@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.4 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
<<<<<<< HEAD
REM Generated by Vivado on Tue Jan 30 14:25:11 -0800 2018
=======
REM Generated by Vivado on Mon Feb 05 13:38:03 -0800 2018
>>>>>>> New-FSM-Test
=======
REM Generated by Vivado on Mon Feb 05 13:43:49 -0800 2018
>>>>>>> New-FSM-Test
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
echo "xvhdl --incr --relax -prj lab2b_tb_vhdl.prj"
call xvhdl  --incr --relax -prj lab2b_tb_vhdl.prj -log xvhdl.log
call type xvhdl.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
